### ISSUE TITLE
Issue with pandas and tables in example data

### ISSUE THREAD

**Issue by Specom** [AdaptiveMotorControlLab/AmadeusGPT#32]
Hey there,

running the "simple_amadeusGPT_demo" in jupyter notebook (windows, anaconda) geives me the following error in the section "set up AmadeusGPT with the data":

**ImportError: Pandas requires version '3.8.0' or newer of 'tables' (version '3.7.0' currently installed).**

I had to install several other packages like google, and restrictedPython, but none of them seem to have updated panda. which version of panda do I need? Installing tables 3.8 gives the error that amadeusgpt needs tables 3.7.

Cheers

Sander

**Comment by yeshaokai** [comment]
@Specom 
Thanks for reporting the issue. I have fixed it in a PR. Feel free to test our new release!
https://github.com/AdaptiveMotorControlLab/AmadeusGPT/tree/release-0.1.0
