### ISSUE TITLE
Wrong link to paper 

### ISSUE THREAD

**Issue by MSchellenberger** [AdaptiveMotorControlLab/AmadeusGPT#35]
Hi,

I found that the link to the paper is actually just directing to a google search. Here´s a functional link to the paper that could be used instead: https://openreview.net/pdf?id=9AcG3Tsyoq

**Comment by yeshaokai** [comment]
@MSchellenberger  Thanks! I updated the link in a PR.
We are testing a new release. Feel free to give us your feedback!
https://github.com/AdaptiveMotorControlLab/AmadeusGPT/tree/release-0.1.0
