### ISSUE TITLE
Actually provide code

### ISSUE THREAD

**Issue by yarikoptic** [AdaptiveMotorControlLab/AmadeusGPT#4]
README says "Code coming soon". I got intrigued. Want to monitor on whenever it comes about.
Interested ones to do the same could subscribe on this issue and wait for it to get closed.

**Comment by MMathisLab** [comment]
hey @yarikoptic thanks! maybe a better discussions topic, but can leave as an issue for now 🤗

**Comment by MMathisLab** [comment]
solved in #10
