### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by DenisKochetov** [AdaptiveMotorControlLab/AmadeusGPT#7]
For any input I get this error today.  
![image](https://github.com/AdaptiveMotorControlLab/AmadeusGPT/assets/57500456/aac3b7ba-af93-4414-a557-992f1f4122e2)

**Comment by yeshaokai** [comment]
I believe it's because the openAI key we provided reached our pay quota. If you use your own API key, it should work.
